services:
  - type: web
    name: roleta-duzia-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend_previsao_duzia:app --host 0.0.0.0 --port=$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
    plan: free
    region: oregon
